"""Added quotes table

Revision ID: 3cb2edc204f6
Revises: 1421080dd6bd
Create Date: 2025-09-02 11:47:32.926866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3cb2edc204f6'
down_revision: Union[str, Sequence[str], None] = '1421080dd6bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_login'), table_name='users')
    op.create_index(op.f('ix_users_username'),
                    'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.create_index(op.f('ix_users_login'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###
